#!/usr/bin/env python3
# encoding=utf-8
# vim: set filetype=python
from appyratus.cli import safe_main

from {{ name|snake }}.svc.api import cli


def main():
    """
    Main execution for {{ name|title }}
    """
    cli.bootstrap()
    cli.start()


if __name__ == "__main__":
    safe_main(main, debug_level=1)
