#!/usr/bin/env python3
# encoding=utf-8
# vim: set filetype=python
import os

from appyratus.cli import safe_main

from {{ name|snake }}.api import cli


def main():
    """
    Main execution for {{ name|title }}
    """
    cli.bootstrap(manifest_filepath=os.path.join(os.path.dirname(__file__), '../manifest.yml'))
    cli.start()


if __name__ == "__main__":
    safe_main(main, debug_level=1)
